### ISSUE TITLE
[Bug Report] Wrong index

### ISSUE THREAD

**Issue by yezhengkai** [solvcon/shocktube1dcalc#6]
## Description
Error in README sample code

## shocktube-1d-caculator version
1.0.1

## Steps to Reproduce
```python
from shocktube1dcalc import cese

elapsed_time = 0.4
cese_grid_size_t = 0.004
# multiply 2 for half grids, so total iteration number should be double
iteration_number = round(elapsed_time / cese_grid_size_t * 2)

shocktube = cese.ShockTube(iteration=iteration_number, grid_size_t=cese_grid_size_t)
shocktube.run_cese_iteration()

numeric_solution = shocktube.data.solution
```

## Actual Behavior
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\side_project\shocktube1dcalc\shocktube1dcalc\cese.py", line 150, in run_cese_iteration
    self._data.refresh_solution()
  File "D:\side_project\shocktube1dcalc\shocktube1dcalc\cese.py", line 342, in refresh_solution
    solution_x = self.mesh_x[i + solution_x_start_index]
IndexError: index 201 is out of bounds for axis 0 with size 201
```

**Comment by tai271828** [comment]
Thanks @yezhengkai  for reporting! I can reproduce this issue.

**Comment by tai271828** [comment]
The iteration number is always less than 1 by the grid number, so `iteration_number` is incorrect.
